import { CustomError } from "./CustomError";

export class NotFoundError extends CustomError {
    constructor(message = "Recurso n√£o encontrado") {
        super(message, 404);
    }
}